export enum ActividadEconomica {
    AGRICULTURA_GANADERIA_CAZA_SILVICULTURA_PESCA = "Agricultura, ganadería, caza, silvicultura y pesca",
    EXPLOTACION_MINAS = "Explotación de minas y canteras",
    INDUSTRIA_MANUFACTURERA = "Industria Manufacturera",
    SUMINISTRO_ELECTRICIDAD_GAS_VAPOR = "Suministro de electricidad, gas, vapor y aire acondicionado",
    SUMINISTRO_AGUA_ALCANTARILLADO = "Suministro de agua, alcantarillado, gestión de desechos",
    ACTIVIDADES_SANEAMIENTO = "Actividades de saneamiento",
    CONSTRUCCION = "Construcción",
    COMERCIO = "Comercio al por mayor y al por menor",
    REPARACION_VEHICULOS = "Reparación de vehículos automotores y motocicletas",
    TRANSPORTE = "Transporte y almacenamiento",
    ALOJAMIENTO = "Alojamiento y servicios de comida",
    COMUNICACION = "Información y comunicación",
    ACTIVIDADES_FINANCIERAS = "Actividades financieras y de seguros",
    ACTIVIDADES_INMOBILIARIAS = "Actividades inmobiliarias",
    ACTIVIDADES_PROFESIONALES = "Actividades profesionales, científicas y técnicas",
    ACTIVIDADES_ADMINISTRATIVAS = "Actividades administrativas y servicios de apoyo",
    ADMINISTRACION_PUBLICA = "Administración pública y defensa",
    PLANES_SEGURO_SOCIAL = "Planes de seguro social obligatorio",
    ENSENANZA = "Enseñanza",
    SALUD = "Salud humana y servicios sociales",
    ARTE = "Arte, entretenimiento y recreación",
    ACTIVIDADES_DOMESTICAS = "Actividades de los hogares como empleadores de personal doméstico",
    ACTIVIDADES_HOGARES_PRODUCTORES = "Actividades de los hogares como productores de bienes o servicios para uso propio",
    ACTIVIDADES_ORGANIZACIONES = "Actividades de organizaciones y organismos extraterritoriales",
    OTRO = "Otras actividades de servicios"
}